version: '3.3'
services:
  web:
    build: .
    # command: chown -R /var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000  
    container_name: jenkins
    volumes:
     - /jenkins_data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock